#!/usr/bin/env bash

if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

echo "Looking for changes..."
files=`git status --porcelain | wc -l`
if [ ${files} == 0 ] ; then
    echo "OK"
else
    echo "FAIL"
    git status
    exit 1
fi

# Check format, lint, run static analyzer.
.githooks/pre-commit || { echo "FAIL"; exit 1; }

# Unit tests with pytest.
echo "Run tests with pytest..."
pytest -vv || { echo "FAIL"; exit 1; }

exit 0
