#!/usr/bin/env bash

if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

echo "Check code format with Ruff..."
if ! ruff format --check; then
    ruff format --diff
    echo "FAIL"
    exit 1
fi

echo "Lint with Ruff..."
ruff check --exclude map_machine/doc/moire_manager.py || { echo "FAIL"; exit 1; }

echo "Check with ty..."
ty check || { echo "FAIL"; exit 1; }

echo "OK"
