include:

  - nodes
  - roads
  - ways
  - keys

options:

  nodes: yes
  trees: yes
  craters: yes
  directions: yes

  buildings: flat
  roads: simple
  mode: normal
  labels: main

  roofs: yes
  building_colors: no
  background: yes

variables:

  # Default colors for icons.
  default: "#444444"
  extra: "#888888"

  # Direction sector colors.
  direction_view_color: "#C8E8FF"
  direction_camera_color: "#0088FF"

  # Main colors.
  background_color: "#EEEEEE"
  road_color: "#FFFFFF"
  road_border_color: "#CCCCCC"
  text_color: "#444444"
  text_main_color: "#000000"
  text_outline_color: "#FFFFFF"

  # Natural land.
  wheat_color: "#F0DCAA"
  wheat_border_color: "#F4D67F"
  wheat_dark_color: "#BF9340"
  rye_color: "#E0CA96"
  rye_dark_color: "#AE955D"
  oat_color: "#EDDDB7"
  oat_dark_color: "#C4894A"
  barley_color: "#F3EEC4"
  barley_border_color: "#D2CE9D"
  barley_dark_color: "#908F62"
  sunflower_dark_color: "#DEAC4A"

  # Buildings.
  building_border_color: "#E0D0C0"
  building_color: "#F8F0E8"
  building_construction_border_color: "#C4C0BC"
  building_construction_color: "#D4D0CC"
  construction_color: "#CCCCCC"

  # Roads.
  # aeroway_color
  bridge_color: "#666666"
  # cycle_border_color
  # cycle_noaccess_color
  cycle_color: "#4444EE"
  cycle_dasharray: 8.0,2.0
  embankment_color: "#666666"
  ford_color: "#88BBFF"
  foot_border_color: "#FFFFFF"
  foot_border_width: 3.0
  # foot_color-noaccess
  foot_color: "#B89A74"
  foot_dasharray: 7.0,3.0
  motorway_border_color: "#CC8800"
  motorway_color: "#FFAA33"
  primary_border_color: "#AA8800"
  primary_color: "#FFDD66"
  secondary_border_color: "#BB9911"
  secondary_color: "#FFEE77"
  tertiary_border_color: "#CCAA22"
  tertiary_color: "#FFFF88"

  # Node colors.
  amenity_brown_color: black
  eat_color: black
  evergreen_color: "#688C44"
  decidious_color: "#FCAF3E"
  sell_color: "#880088"
  # sell_text_color
  craft_color: "#008800"

  # Land cover.
  cemetery_color: black
  cemetery_opacity: 0.05
  commercial_border_color: black
  commercial_border_width: 0.0
  commercial_color: black
  commercial_opacity: 0.05
  wood_color: "#B8CC84"
  # golf_course_color
  # mud
  # place_of_worship_outline
  # power-line
  # power
  # societal_amenities_color
  # track
  # wastewater_plant_border_color
  # wastewater_plant_color
  # water_works-line
  # water_works
  # apron_color
  # bare_ground_color
  beach_color: "#F0E0C0"
  # campsite_color
  farmland_border_color: "#DDCC99"
  farmland_color: "#FFEEBB"
  farmland_darker_color: "#998855"
  industrial_border_color: black
  industrial_border_width: 0.0
  industrial_color: black
  industrial_opacity: 0.05
  military_color: black
  military_opacity: 0.05
  # aboriginal
  # airtrnsport
  allotments_color: "#D0E0D0"
  # barrier_color
  boundary_color: "#880088"
  # bridleway_border_color
  # bridleway_color-noaccess
  # bridleway_color
  desert_color: "#F0E0D0"
  emergency_color: "#DD2222"
  # farmyard_border_color
  # farmyard_color
  # garages_color
  ferry_terminal_color: "#AABBDD"
  foot_area_border_color: "#BBBBBB"
  foot_area_color: "#DDDDDD"
  grass_color: "#CFE0A8"
  grass_border_color: "#BFD098"
  health_color: black
  # heath_color
  hidden_color: "#000000"
  # industrial_border_color
  # industrial_color
  indoor_border_color: "#A0A890"
  indoor_color: "#E8E4E0"
  indoor_column_color: {color: $indoor_border_color, darken: 0.5}
  kindergarten_color: black
  kindergarten_opacity: 0.05
  # landform_color
  # leisure_color
  # leisure_green_color
  # living_street_border_color
  # living_street_color
  # man_made_color
  # marina_text_color
  meadow_border_color: "#BFD078"
  meadow_color: "#CFE088"
  # militaty_color
  # office_color
  orchard_border_color: "#98BC84"
  orchard_color: "#B8DCA4"
  outline_color: "#FFFFFF"
  park_color: "#CFE0A8"
  park_opacity: 0.5
  parking_border_color: black
  parking_color: "#DDCC99"
  parking_node_color: black
  parking_opacity: 0.5
  parking_stroke_width: 0
  # path_border_color
  # pedestrian_border_color
  # pedestrian_color
  pitch_border_color: "#88BBAA"
  pitch_color: "#AADDCC"
  # place_of_worship_color
  platform_border_color: "#AAAAAA"
  platform_color: "#CCCCCC"
  playground_border_color: "#FFAA88"
  playground_border_width: 1.0
  playground_color: "#FFDDCC"
  # protected_area_color
  # quarry_color
  # raceway_color
  railway_border_color: black
  railway_border_width: 0.0
  railway_color: black
  railway_opacity: 0.05
  residential_area_border_color: black
  residential_area_border_width: 0.1
  residential_area_color: black
  residential_area_opacity: 0.05
  # residential_border_colo
  # residential_color
  # rest_area_color
  retail_border_color: black
  retail_border_width: 0.0
  retail_color: black
  retail_opacity: 0.05
  ridge_color: "#000000"
  # road_border_color
  rock_color: "#DDDDDD"
  route_color: "#FFFFFF"
  runway_border_color: {color: $runway_color, darken: 0.25}
  runway_color: "#999399"
  sand_color: "#E8E0C0"
  school_color: black
  school_opacity: 0.05
  scree_color: "#CCCCCC"
  # service_border_color
  # service_color
  # steps_border_color
  # steps_noaccess_color
  # steps_color
  swimming_area_color: "#80D0F0"
  # tourism_color
  taxiway_border_color: {color: $taxiway_color, darken: 0.25}
  taxiway_color: "#AAA4AA"
  # track_border_color
  # track_noaccess_color
  track_color: "#A88A64"
  track_grade_2_dasharray: no
  track_grade_3_dasharray: no
  track_grade_4_dasharray: no
  track_grade_5_dasharray: no
  track_grade_no_dasharray: no
  # transportation_area_color
  # transportation_color
  # transportation_text_color
  tree_color: "#98AC64"
  # trunk_border_color
  trunk_color: "#97612b"








  village_green_color: "#DDEEBB"
  wall_bottom_1_color: "#AAAAAA"
  wall_bottom_2_color: "#C3C3C3"
  wall_color: "#E8E8E8"
  wall_construction_color: "#84807C"
  water_border_color: "#6688BB"
  water_color: "#80C8F0"
  wetland_color: "#BFE0D8"
  wood_border_color: "#A8BC74"

  stadium_color: $grass_color
  stadium_opacity: 0.5
  stadium_border_color: black
  stadium_border_width: 0.0
  sports_centre_color: $grass_color
  sports_centre_opacity: 0.5
  sports_centre_border_color: black
  sports_centre_border_width: 0.0
  water_park_color: $grass_color
  water_park_opacity: 0.5
  water_park_border_color: black
  water_park_border_width: 0.0

  # Colors not in W3C.
  rose: "#FF007F"  # Wikipedia.
  slate_blue: "#6A5ACD"  # W3C slateblue.
  bronze: "#CD7F32"
  concrete: "#AAAAAA"
  glass: "#CCEEFF"
