#!/usr/bin/env bash

python_files="map_machine tests data/githooks/commit-msg"

source .venv/bin/activate

echo "Checking code format..."
if ! ruff format --check; then
    ruff format --diff
    echo "FAIL"
    exit 1
fi

# Link with Flake8.

echo "Lint with Flake8..."
flake8 \
    --max-line-length=80 \
    --ignore=E203,W503,ANN002,ANN003,ANN101,ANN102 \
    ${python_files} \
    || { echo "FAIL"; exit 1; }
