#!/bin/sh

echo "Checking code format with Black..."
if ! black -l 80 --check tests roentgen; then
    black -l 80 --diff tests roentgen
    echo "FAIL"
    exit 1
fi

# Link with Flake8.

echo "Lint with Flake8..."
flake8 \
    --max-line-length=80 \
    --ignore=E203,W503,ANN002,ANN003,ANN101,ANN102 \
    --exclude=work,precommit.py,tests/test_road.py \
    || { echo "FAIL"; exit 1; }
