name: Test for Python 3.8

on:
  push:
    branches: [python3.8]
  pull_request:
    branches: [python3.8]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest
        pip install -r requirements.txt
        pip install .
    - name: Check code style with Black
      run: |
        black -l 80 --check map_machine tests
    - name: Lint with Flake8
      run: |
        flake8 --max-line-length=80 --ignore=E203,W503
    - name: Test with pytest
      run: |
        pytest -v
